#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 23 17:20:07 2018

@author: sathisanvannadil
"""
import json

with open('myJson.json', 'r') as f:
    docid_to_title_new = json.load(f)


ml = [] 
for i in docid_to_title_new.keys():
    ml += docid_to_title_new[i]['content']['title'].split(' ')    
print(len(ml))
print(len(set(ml)))
print(ml)